# ============================================
# CELL 1: NIFTY 750 MARKET CAP CATEGORIES (CONSTANT)
# ============================================

LARGE_CAP_SYMBOLS = [
    'HDFCBANK', 'RELIANCE', 'ICICIBANK', 'TCS', 'INFY', 'AXISBANK', 'SBIN',
    'BHARTIARTL', 'LT', 'WIPRO', 'ETERNAL', 'ADANIPOWER', 'M&M', 'ADANIENSOL',
    'KOTAKBANK', 'BAJFINANCE', 'ADANIGREEN', 'BAJAJ-AUTO', 'ASIANPAINT', 'TMCV',
    'TITAN', 'LODHA', 'CUMMINSIND', 'MARUTI', 'HINDALCO', 'ADANIPORTS', 'INDIGO',
    'TATASTEEL', 'NTPC', 'ABB', 'ITC', 'HAL', 'EICHERMOT', 'TVSMOTOR', 'MAZDOCK',
    'HCLTECH', 'ULTRACEMCO', 'BEL', 'TRENT', 'HINDUNILVR', 'POWERGRID', 'MAXHEALTH',
    'ONGC', 'CHOLAFIN', 'TMPV', 'DLF', 'ADANIENT', 'APOLLOHOSP', 'BOSCHLTD',
    'MOTHERSON', 'MUTHOOTFIN', 'SBILIFE', 'TORNTPHARM', 'SOLARINDS', 'TECHM',
    'CANBK', 'JIOFIN', 'BANKBARODA', 'HDFCLIFE', 'CIPLA', 'VBL', 'UNIONBANK',
    'TATAPOWER', 'HDFCAMC', 'DRREDDY', 'RECLTD', 'HINDZINC', 'PIDILITIND', 'GAIL',
    'SIEMENS', 'IRFC', 'JSWSTEEL', 'DIVISLAB', 'UNITDSPR', 'JINDALSTEL', 'IOC',
    'PNB', 'DMART', 'LTM', 'BRITANNIA', 'SHREECEM', 'AMBUJACEM', 'CGPOWER',
    'GODREJCP', 'INDHOTEL', 'HYUNDAI', 'ENRIN', 'ZYDUSLIFE', 'BAJAJHLDNG',
    'TATACAP', 'PFC', 'VEDL', 'NATIONALUM', 'PERSISTENT', 'COALINDIA', 'SUNPHARMA',
    'GRASIM', 'NESTLEIND', 'TATACONSUM', 'PAGEIND', 'MRF', 'COLPAL'
]

MID_CAP_SYMBOLS = [
    'BSE', 'GROWW', 'NIACL', 'DIXON', 'POWERINDIA', 'MCX', 'WAAREEENER', 'ASHOKLEY',
    'COFORGE', 'GVT&D', 'HEROMOTOCO', 'COCHINSHIP', 'ATGL', 'IDEA', 'BHEL', 'BPCL',
    'GODREJPROP', 'POLYCAB', 'NAUKRI', 'PRESTIGE', 'SUZLON', 'ICICIAMC', 'LUPIN',
    'PAYTM', 'GODFRYPHLP', 'BHARATFORG', 'FEDERALBNK', 'LENSKART', 'SAIL',
    'POLICYBZR', 'MPHASIS', 'HINDPETRO', 'RVNL', 'INDUSTOWER', 'LICI', 'NMDC',
    'INDIANB', 'LAURUSLABS', 'NAM-INDIA', 'APARINDS', 'KALYANKJIL', 'SRF', 'VOLTAS',
    'AUBANK', 'ASTRAL', 'GMRAIRPORT', 'MARICO', 'PHOENIXLTD', 'MFSL', 'BDL',
    'ABCAPITAL', 'LTF', 'YESBANK', 'JUBLFOOD', 'GLENMARK', 'BANKINDIA', 'UPL', 'KEI',
    'NHPC', 'PREMIERENE', 'EXIDEIND', 'IDFCFIRSTB', 'COROMANDEL', 'INDUSINDBK',
    'AUROPHARMA', 'MAHABANK', 'RADICO', 'IREDA', 'GICRE', 'OIL', 'OFSS', 'KPITTECH',
    'JSWENERGY', 'BLUESTARCO', 'OBEROIRLTY', 'PETRONET', 'VMM', 'DABUR', 'SUPREMEIND',
    'HAVELLS', 'TATAELXSI', 'THERMAX', 'NYKAA', 'M&MFIN', 'CONCOR', 'MOTILALOFS',
    'APLAPOLLO', 'ITCHOTELS', 'AWL', 'LGEINDIA', 'ICICIGI', 'BIOCON', 'SUNDARMFIN',
    'IRCTC', 'LTTS', 'BAJAJHFL', 'MANKIND', 'LLOYDSME', 'FORTIS', 'TIINDIA', 'JSL',
    'TATACOMM', 'SCHAEFFLER', 'KPRMILL', 'BALKRISIND', 'LICHSGFIN', 'PATANJALI',
    'ALKEM', 'JKCEMENT', 'DALBHARAT', 'SBICARD', 'ICICIPRULI', 'HUDCO', 'TORNTPOWER',
    'APOLLOTYRE', 'PIIND', 'ESCORTS', 'NLCINDIA', 'LINDEINDIA', 'ANTHEM', 'SJVN',
    'BERGEPAINT', 'AIAENG', 'CRISIL', 'ACC', 'HONAUT', 'ABBOTINDIA', 'UBL', 'HDBFS',
    'ENDURANCE', 'AJANTPHARM', 'GODREJIND', 'AIIL', 'MEDANTA', 'GLAXO', 'IPCALAB',
    'BHARTIHEXA', '3MINDIA', 'FLUOROCHEM'
]

SMALL_CAP_SYMBOLS = [
    'OLAELEC', 'COHANCE', 'ATHERENERG', 'GRSE', 'HFCL', 'KAYNES', 'FORCEMOT',
    'ANGELONE', 'OLECTRA', 'CDSL', 'AMBER', 'NETWEB', 'DATAPATTNS', 'SAMMAANCAP',
    'SONACOMS', 'HINDCOPPER', 'MEESHO', 'POONAWALLA', 'PGEL', 'TEJASNET', 'ITI',
    'ZEEL', 'CHENNPETRO', 'RBLBANK', 'JPPOWER', 'BELRISE', 'EMMVEE', 'RPOWER',
    'ABREL', 'IGL', 'ACE', 'JBMA', 'GALLANTT', 'NAVINFLUOR', 'GMDCLTD', 'IDBI',
    'DEVYANI', 'REDINGTON', 'HBLENGINE', 'KFINTECH', 'KIMS', 'ONESOURCE', 'TARIL',
    'HSCL', 'SCI', 'ABDL', 'TATACHEM', 'BLS', 'IRB', 'SYNGENE', 'BANDHANBNK',
    'KARURVYSYA', 'MANAPPURAM', 'FIRSTCRY', 'ANANTRAJ', 'ZENTEC', 'DELHIVERY',
    'TTML', 'SYRMA', 'SAPPHIRE', 'CONCORDBIO', 'NBCC', 'IFCI', 'MRPL', 'ENGINERSIN',
    'ABFRL', 'PINELABS', 'HONASA', 'NEULANDLAB', 'KIRLOSENG', 'NATCOPHARM',
    'MINDACORP', 'CROMPTON', 'ACUTAAS', 'KEC', 'APTUS', 'JWL', 'JBCHEPHARM',
    'INOXWIND', 'ABSLAMC', 'CHOICEIN', 'IRCON', 'WOCKPHARMA', 'SBFC', 'LEMONTREE',
    'RAILTEL', 'HEG', 'IIFL', 'CAMS', 'ECLERX', 'GPIL', 'CARTRADE', 'NCC', 'JKTYRE',
    'NEWGEN', 'PARADEEP', 'IEX', 'ARE&M', 'LALPATHLAB', 'MGL', 'WELCORP',
    'INDIAMART', 'BRIGADE', 'JYOTICNC', 'DEEPAKNTR', 'ELECON', 'TITAGARH',
    'JMFINANCIL', 'FIVESTAR', 'EMCURE', 'JINDALSAW', 'GRANULES', 'BSOFT',
    'PIRAMALFIN', 'IKS', 'DEEPAKFERT', 'JAINREC', 'NSLNISP', 'TATATECH', 'GESHIP',
    'GRAPHITE', 'J&KBANK', 'GRAVITA', 'CYIENT', 'VTL', 'CEATLTD', 'AAVAS',
    'PNBHOUSING', 'PWL', 'GABRIEL', 'MANYAVAR', 'CHOLAHLDNG', 'AFFLE', 'PPLPHARMA',
    'FACT', 'BEML', 'ELGIEQUIP', 'AARTIIND', 'BLUEJET', 'ASTERDM', 'CARBORUNIV',
    'HOMEFIRST', 'RAMCOCEM', 'ANURAS', 'SAILIFE', 'TEGA', 'KAJARIACER', 'NAVA',
    'SIGNATURE', 'SAREGAMA', 'NH', 'NUVAMA', 'MSUMI', 'PCBL', 'UTIAMC', 'TRITURBINE',
    'AADHARHFC', 'GILLETTE', 'BALRAMCHIN', 'CREDITACC', 'CEMPRO', 'SCHNEIDER',
    'EMAMILTD', 'LATENTVIEW', 'FINCABLES', 'CRAFTSMAN', 'CASTROLIND', 'ACMESOLAR',
    'CCL', 'STARHEALTH', 'KPIL', 'SWANCORP', 'EIHOTEL', 'CLEAN', 'SARDAEN',
    'TECHNOE', 'GSPL', 'LTFOODS', 'MMTC', 'THELEELA', 'SOBHA', 'AEGISVOPAK',
    'AKZOINDIA', 'PVRINOX', 'ZYDUSWELL', 'RRKABEL', 'ZENSARTECH', 'SHYAMMETL',
    'SUNTV', 'CENTRALBK', 'TENNIND', 'CESC', 'RITES', 'AFCONS', 'RAINBOW', 'CGCL',
    'JSWCEMENT', 'TRIDENT', 'UCOBANK', 'CAPLIPOINT', 'CHAMBLFERT', 'CPPLUS', 'BBTC',
    'ATUL', 'JUBLPHARMA', 'FSL', 'JUBLINGREA', 'POLYMED', 'IOB', 'INTELLECT',
    'TIMKEN', 'MAPMYINDIA', 'EIDPARRY', 'RKFORGE', 'USHAMART', 'WHIRLPOOL',
    'SONATSOFTW', 'IGIL', 'BATAINDIA', 'GLAND', 'BLUEDART', 'BAYERCROP', 'NUVOCO',
    'TBOTEK', 'CANFINHOME', 'WELSPUNLIV', 'ERIS', 'SPLPETRO', 'TRAVELFOOD', 'DOMS',
    'INDIACEM', 'NIVABUPA', 'PFIZER', 'GODIGIT', 'CHALET', 'SUMICHEM', 'ASAHIINDIA',
    'ABLBL', 'CANHLIFE', 'VIJAYA', 'RHIM', 'INDGN', 'DCMSHRIRAM', 'BIKAJI'
]

MICRO_CAP_SYMBOLS = [
    'AVANTIFEED', 'MTARTECH', 'TDPOWERSYS', 'STLTECH', 'SHRIPISTON', 'VIKRAMSOLR',
    'CUPID', 'AEQUS', 'LUMAXTECH', 'QPOWER', 'HCC', 'INOXINDIA', 'SAATVIKGL',
    'SANSERA', 'POWERMECH', 'PFOCUS', 'TRANSRAILL', 'SHAILY', 'VOLTAMP',
    'TIMETECHNO', 'PCJEWELLER', 'SHAKTIPUMP', 'UJJIVANSFB', 'KTKBANK', 'KRN',
    'THANGAMAYL', 'RUBICON', 'YATHARTH', 'JAYNECOIND', 'AETHER', 'AVALON', 'WABAG',
    'VMART', 'PARAS', 'SKYGOLD', 'ZAGGLE', 'SOUTHBANK', 'GOKEX', 'EDELWEISS',
    'AURIONPRO', 'ATLANTAELE', 'SENCO', 'JAMNAAUTO', 'HAPPSTMNDS', 'DCBBANK',
    'RAIN', 'BLACKBUCK', 'EPL', 'ELLEN', 'WAAREERTL', 'WEBELSOLAR', 'BBOX',
    'BORORENEW', 'KSCL', 'PNGJL', 'OSWALPUMPS', 'LLOYDSENGG', 'SHARDACROP',
    'SWSOLAR', 'SPARC', 'KNRCON', 'AZAD', 'SMLMAH', 'DBREALTY', 'KPIGREEN',
    'LLOYDSENT', 'ELECTCAST', 'PRAJIND', 'GPPL', 'PRIVISCL', 'RCF', 'IXIGO',
    'RTNINDIA', 'GOKULAGRO', 'TANLA', 'ASTRAMICRO', 'DIACABS', 'SANDUMA',
    'AXISCADES', 'PARKHOSPS', 'BANCOINDIA', 'MOIL', 'STAR', 'MIDHANI', 'LOTUSDEV',
    'V2RETAIL', 'RTNPOWER', 'IMFA', 'PURVA', 'MANORAMA', 'THOMASCOOK', 'RENUKA',
    'INOXGREEN', 'BLUESTONE', 'HGINFRA', 'DYNAMATECH', 'TI', 'AVL', 'IIFLCAPS',
    'KSB', 'KRBL', 'BALUFORGE', 'GSFC', 'CRAMC', 'HERITGFOOD', 'JAIBALAJI', 'NFL',
    'NAZARA', 'VIYASH', 'ASHAPURMIN', 'ASHOKA', 'KITEX', 'RELIGARE', 'EIEL',
    'NETWORK18', 'KANSAINER', 'SHILPAMED', 'ATUL', 'CCAVENUE', 'GREAVESCOT',
    'PRUDENT', 'EQUITASBNK', 'JSLL', 'VGUARD', 'SKFINDIA', 'MAHSEAMLES', 'AKUMS',
    'GAEL', 'TARC', 'MEDPLUS', 'ARVINDFASN', 'ROUTE', 'TMB', 'FIEMIND',
    'INDIGOPNTS', 'RELAXO', 'JUSTDIAL', 'PRICOLLTD', 'KIRLOSBROS', 'PTC', 'VARROC',
    'STYL', 'PNCINFRA', 'SAMHI', 'FINPIPE', 'CERA', 'BIRLACORPN', 'CIGNITITEC',
    'ANUP', 'MASTEK', 'CSBBANK', 'JSFB', 'CMSINFO', 'ALOKINDS', 'RATEGAIN',
    'GMRP&UI', 'ICIL', 'BECTORFOOD', 'REFEX', 'HEMIPROP', 'RBA', 'INDIAGLYCO',
    'GRWRHITECH', 'WELENT', 'SUDARSCHEM', 'BAJAJELEC', 'OPTIEMUS', 'CIEINDIA',
    'RAYMONDLSL', 'IFBIND', 'JKLAKSHMI', 'FEDFINA', 'GNFC', 'GODREJAGRO', 'SKIPPER',
    'MARKSANS', 'IONEXCHANG', 'INDIASHLTR', 'NEOGEN', 'AARTIDRUGS', 'ARVIND',
    'UTLSOLAR', 'LXCHEM', 'EUREKAFORB', 'JKPAPER', 'ACI', 'MSTCLTD', 'BALAMINES',
    'ORKLAINDIA', 'AARTIPHARM', 'JYOTHYLAB', 'TRIVENI', 'DBL', 'SUNTECK',
    'METROPOLIS', 'AWFIS', 'VIPIND', 'EMIL', 'ASKAUTOLTD', 'THYROCARE', 'RALLIS',
    'PICCADIL', 'ALKYLAMINE', 'SHAREINDIA', 'VAIBHAVGBL', 'DATAMATICS', 'SURYAROSNI',
    'ALIVUS', 'CENTURYPLY', 'WESTLIFE', 'ADVENZYMES', 'SUBROS', 'CAMPUS', 'HCG',
    'WEWORK', 'PGIL', 'KIRLPNU', 'SFL', 'MAHSCOOTER', 'QUESS', 'ENTERO', 'NESCO',
    'CRIZAC', 'SAFARI', 'TVSSCS', 'SUPRIYA', 'TSFINV', 'CORONA', 'STYRENIX',
    'GHCL', 'CAPILLARY', 'ETHOSLTD', 'SMARTWORKS', 'ORIENTCEM', 'AHLUCONT',
    'REDTAPE', 'APLLTD', 'AGARWALEYE', 'TIPSMUSIC', 'SUDEEPPHRM', 'GMMPFAUDLR',
    'STARCEMENT', 'PRSMJOHNSN', 'SKFINDUS', 'WAKEFIT', 'JLHL'
]

# Create mapping
SYMBOL_TO_SEGMENT = {}
for s in LARGE_CAP_SYMBOLS: SYMBOL_TO_SEGMENT[s] = 'LARGE'
for s in MID_CAP_SYMBOLS: SYMBOL_TO_SEGMENT[s] = 'MID'
for s in SMALL_CAP_SYMBOLS: SYMBOL_TO_SEGMENT[s] = 'SMALL'
for s in MICRO_CAP_SYMBOLS: SYMBOL_TO_SEGMENT[s] = 'MICRO'

ALL_SYMBOLS = list(SYMBOL_TO_SEGMENT.keys())

if __name__ == "__main__":
    print(f"✅ Loaded {len(ALL_SYMBOLS)} NIFTY 750 stocks")
    print(f"   LARGE: {len(LARGE_CAP_SYMBOLS)}")
    print(f"   MID: {len(MID_CAP_SYMBOLS)}")
    print(f"   SMALL: {len(SMALL_CAP_SYMBOLS)}")
    print(f"   MICRO: {len(MICRO_CAP_SYMBOLS)}")